trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TFSec
    displayName: TFSec
    jobs:
      - job: ScanCodeTFsec
        steps:
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
  - stage: TerraformInit
    displayName: TerraformInit
    jobs:
     - job: job1
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformInitTask
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'Env'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'new.tfstate'

  - stage: TerraformPlan
    displayName: TerraformPlanStage
    jobs:
     - job: job1
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformPlanTaskwithInit
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'Env'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'new.tfstate'
       - task: TerraformTaskV4@4
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: 'Env'
           environmentServiceNameAzureRM: 'Azure-conn-service'




  - stage: TerraformApply
    displayName: TerraformApplyStage
    jobs:
     - job: Apply
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformPlanTaskwithInt
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'Env'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'new.tfstate'    
       - task: TerraformTaskV4@4
         inputs:
           provider: 'azurerm'
           command: 'apply'
           environmentServiceNameAzureRM: 'Azure-conn-service'
