name: terrafrom-code

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformInit
    displayName: TerraformInit
    jobs:
     - job: job1
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformInitTask
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'terraform.tfstate'