trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: codsScan
    displayName: TFScan
    jobs:
      - job: TerraformCodeScan
        steps:
          - task: tfsec@1
            inputs:
             version: 'v1.26.0'
             dir: 'Env'
  - stage: TerraformInit
    displayName: TerraformInit
    jobs:
     - job: job1
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformInitTask
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'Env'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'new.tfstate'

  - stage: TerraformPlan
    displayName: TerraformPlanStage
    jobs:
     - job: Plan
       steps:
       - task: TerraformTaskV4@4
         displayName: TerraformPlanTaskwithInit
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'Env'
           backendServiceArm: 'Azure-conn-service'
           backendAzureRmResourceGroupName: 'bipin-rg'
           backendAzureRmStorageAccountName: 'autostore123'
           backendAzureRmContainerName: 'autostate'
           backendAzureRmKey: 'new.tfstate'
       - task: TerraformTaskV4@4
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: 'Env'
           environmentServiceNameAzureRM: 'Azure-conn-service'

  - stage: 
    displayName: Apply 
    jobs:
    - job: Manualvalidation
      
      displayName: validation
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
         notifyUsers: 'ravisunravi@gmail.com'
         instructions: 'review'

    - job: applychange
      dependsOn: Manualvalidation
      steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: 'Env'
            environmentServiceNameAzureRM: 'Azure-conn-service'

      
